"""Current GAS sheet contract; regression-tested against its schema registry."""

from core.account_detail_contracts import CONTRACTS

DETAIL_HEADERS = {name: contract.headers for name, contract in CONTRACTS.items()}

HEADERS = {
    "account_types": (
        "id",
        "account_type_key",
        "account_type_label",
        "account_subtype_key",
        "account_subtype_label",
        "description",
        "is_loan",
        "detail_sheet",
        "record_status",
        "sync_status",
        "sync_date",
        "sync_notes",
        "created_at",
        "updated_at",
    ),
    "category_master": (
        "id",
        "tx_type_key",
        "tx_type_label",
        "major_category_key",
        "major_category_label",
        "minor_category_key",
        "minor_category_label",
        "description",
        "tag_keywords",
        "counterparty_examples",
        "source_account_types",
        "target_account_types",
        "source_account_mandatory",
        "target_account_mandatory",
        "is_subscription_eligible",
        "record_status",
        "sync_status",
        "sync_date",
        "sync_notes",
        "created_at",
        "updated_at",
    ),
    "account_master": (
        "id",
        "account_name",
        "legal_entity_name",
        "type",
        "sub_type",
        "account_currency_local",
        "local_timezone",
        "account_opening_date_local",
        "account_closing_date_local",
        "opening_value_local",
        "current_value_local",
        "description",
        "record_status",
        "sync_status",
        "sync_date",
        "sync_notes",
        "created_at",
        "updated_at",
        "tracking_start_date_local",
    ),
    "transaction_master": (
        "id",
        "tx_date_local",
        "tx_timezone_local",
        "parent_tx_id",
        "tx_type",
        "account_id",
        "tx_amount_local",
        "major_category",
        "minor_category",
        "description",
        "counterparty_name",
        "tx_tags",
        "beneficiaries",
        "user_location_area",
        "user_location_city",
        "user_location_country",
        "user_location_latitude",
        "user_location_longitude",
        "record_status",
        "sync_status",
        "sync_date",
        "sync_notes",
        "created_at",
        "updated_at",
    ),
    "subscription_master": (
        "id",
        "subscription_name",
        "counterparty_name",
        "subscription_amount_local",
        "frequency",
        "day_of_month",
        "day_of_week",
        "source_account",
        "tx_type",
        "major_category",
        "minor_category",
        "description",
        "record_status",
        "created_at",
        "sync_status",
        "sync_date",
        "sync_notes",
        "updated_at",
        "subscription_start_date_local",
        "subscription_end_date_local",
        "subscription_timezone_local",
    ),
    **DETAIL_HEADERS,
}
