[databases.postgres]
host              = "${FULCRUM_DB_HOST}"
port              = "${FULCRUM_DB_PORT}"
user              = "${FULCRUM_DB_USER}"
password          = "${FULCRUM_DB_PASSWORD}"
connect_database  = "${FULCRUM_DB_NAME}"
migrations_path   = "migrations"
schema            = "public"
tracking_table    = "schema_migrations_ledger_extract"
