"""Writes expense-tracker/api/report-contract.gs from the contract JSON files.

GAS cannot read repository files at runtime, so it gets a generated copy. Keys starting with
"_" (comments) are left out. Run after any change to the JSON files:

    python3 data-synchronization/analytics/contract/generate_gas.py          # write
    python3 data-synchronization/analytics/contract/generate_gas.py --check  # fail if out of date

expense-tracker/tests/report-contract.cjs fails when the copy differs from the JSON.
Standard library only, so it runs before the analytics module has a virtualenv.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

CONTRACT_DIR = Path(__file__).resolve().parent
TARGET = CONTRACT_DIR.parents[2] / "expense-tracker" / "api" / "report-contract.gs"
SOURCES = {"REPORT_DEFINITION": "report-definition.json", "REPORT_PREDEFINED": "predefined-reports.json", "REPORT_SHEET_TABS": "sheet-tabs.json"}


def strip_comments(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: strip_comments(item) for key, item in value.items() if not key.startswith("_")}
    if isinstance(value, list):
        return [strip_comments(item) for item in value]
    return value


def render() -> str:
    loaded = {name: json.loads((CONTRACT_DIR / file).read_text()) for name, file in SOURCES.items()}
    versions = {data["contract_version"] for data in loaded.values()}
    if len(versions) != 1:
        raise SystemExit(f"contract_version differs between files: {sorted(versions)}")
    lines = [
        "// GENERATED by data-synchronization/analytics/contract/generate_gas.py from",
        "// report-definition.json, predefined-reports.json and sheet-tabs.json. Do not edit; regenerate.",
        f"// contract_version {versions.pop()}",
        "",
    ]
    for name, data in loaded.items():
        lines.append(f"const {name} = {json.dumps(strip_comments(data), indent=2, ensure_ascii=False)};")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    text = render()
    if "--check" in sys.argv[1:]:
        if not TARGET.is_file() or TARGET.read_text() != text:
            raise SystemExit(f"{TARGET.name} is out of date: run generate_gas.py")
        print(f"{TARGET.name} is up to date")
        return
    TARGET.write_text(text)
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
